import { createUseStyles } from 'react-jss';

export const useStyles = createUseStyles(theme => ({
    container: {
        marginTop: 32,
        color: theme.colors?.mainText || '#333',
    },
    title: {
        fontSize: 22,
        margin: '0 0 16px',
    },
    loginPrompt: {
        padding: 16,
        background: theme.colors?.paper || '#fff',
        borderRadius: 8,
        textAlign: 'center',
        opacity: 0.85,
        '& a': { color: theme.colors?.buttonBackground || '#ff00a2', fontWeight: 600 },
    },
    composer: {
        display: 'flex',
        flexDirection: 'column',
        gap: 8,
        background: theme.colors?.paper || '#fff',
        padding: 12,
        borderRadius: 8,
        marginBottom: 12,
    },
    textarea: {
        width: '100%',
        boxSizing: 'border-box',
        resize: 'vertical',
        minHeight: 48,
        border: `1px solid ${theme.colors?.selectedOutline || 'rgba(0,0,0,0.15)'}`,
        borderRadius: 6,
        padding: 10,
        fontFamily: 'inherit',
        fontSize: 14,
        color: 'inherit',
        background: 'transparent',
        outline: 'none',
        display: 'block',
        '&:focus': { borderColor: theme.colors?.buttonBackground || '#ff00a2' },
    },
    composerFooter: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: 8,
    },
    counter: {
        opacity: 0.5,
        fontSize: 12,
    },
    composerActions: {
        display: 'flex',
        gap: 8,
        alignItems: 'center',
    },
    cancelBtn: {
        background: 'transparent',
        border: 'none',
        color: 'inherit',
        cursor: 'pointer',
        opacity: 0.7,
        padding: '4px 8px',
        '&:hover': { opacity: 1 },
    },
    list: {
        display: 'flex',
        flexDirection: 'column',
        gap: 16,
    },
    thread: {
        display: 'flex',
        flexDirection: 'column',
        gap: 8,
    },
    comment: {
        display: 'flex',
        gap: 12,
        alignItems: 'flex-start',
    },
    reply: {
        display: 'flex',
        gap: 10,
        alignItems: 'flex-start',
        marginLeft: 48,
    },
    repliesBlock: {
        display: 'flex',
        flexDirection: 'column',
        gap: 10,
        marginTop: 2,
    },
    body: {
        flex: 1,
        minWidth: 0,
    },
    meta: {
        display: 'flex',
        alignItems: 'center',
        gap: 6,
        fontSize: 13,
    },
    name: {
        fontWeight: 600,
        color: 'inherit',
        textDecoration: 'none',
        '&:hover': { textDecoration: 'underline' },
    },
    opBadge: {
        fontSize: 10,
        fontWeight: 700,
        padding: '1px 6px',
        borderRadius: 999,
        background: theme.colors?.buttonBackground || '#ff00a2',
        color: theme.colors?.buttonText || '#fff',
        letterSpacing: 0.5,
    },
    time: {
        opacity: 0.55,
        fontSize: 12,
    },
    text: {
        marginTop: 4,
        whiteSpace: 'pre-wrap',
        wordBreak: 'break-word',
        fontSize: 14,
    },
    actions: {
        display: 'flex',
        gap: 12,
        marginTop: 4,
    },
    actionBtn: {
        background: 'transparent',
        border: 'none',
        padding: 0,
        fontSize: 12,
        cursor: 'pointer',
        color: 'inherit',
        opacity: 0.6,
        '&:hover': { opacity: 1, textDecoration: 'underline' },
    },
    showMore: {
        marginLeft: 48,
        background: 'transparent',
        border: 'none',
        color: theme.colors?.buttonBackground || '#ff00a2',
        fontSize: 13,
        cursor: 'pointer',
        padding: '4px 0',
        textAlign: 'left',
        '&:hover': { textDecoration: 'underline' },
    },
    error: {
        color: '#e5005d',
        fontSize: 12,
    },
    status: {
        opacity: 0.6,
        textAlign: 'center',
        padding: 16,
        fontSize: 14,
    },
}));
