import { createUseStyles } from 'react-jss';

export const useStyles = createUseStyles(theme => ({
    container: {
        padding: 24,
        color: theme.colors?.mainText || '#333',
        maxWidth: 1200,
        margin: '0 auto',
    },
    profileRow: {
        display: 'flex',
        alignItems: 'center',
        gap: 16,
        padding: 16,
        background: theme.colors?.paper || '#222',
        borderRadius: 12,
        marginBottom: 20,
    },
    profileText: { flex: 1, display: 'flex', flexDirection: 'column' },
    profileName: {
        fontSize: 18,
        fontWeight: 600,
        color: 'inherit',
        textDecoration: 'none',
        '&:hover': { textDecoration: 'underline' },
    },
    profileHandle: { opacity: 0.6, fontSize: 14 },
    settingsLink: {
        color: 'inherit',
        textDecoration: 'none',
        padding: '8px 14px',
        borderRadius: 8,
        border: `1px solid ${theme.colors?.selectedFrame || '#444'}`,
        fontSize: 14,
        '&:hover': { background: 'rgba(255,255,255,0.05)' },
    },
    tabs: {
        display: 'flex',
        gap: 8,
        marginBottom: 24,
    },
    tab: {
        padding: '8px 16px',
        borderRadius: 8,
        border: 'none',
        cursor: 'pointer',
        background: 'transparent',
        color: 'inherit',
        fontSize: 16,
        opacity: 0.6,
    },
    tabActive: {
        padding: '8px 16px',
        borderRadius: 8,
        border: 'none',
        cursor: 'pointer',
        background: theme.colors?.buttonBackground || '#333',
        color: 'inherit',
        fontSize: 16,
    },
    grid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))',
        gap: 16,
    },
    card: {
        backgroundColor: theme.colors?.paper || '#222',
        borderRadius: 8,
        overflow: 'hidden',
        textDecoration: 'none',
        color: 'inherit',
        display: 'flex',
        flexDirection: 'column',
        cursor: 'pointer',
        transition: 'transform 0.15s',
        '&:hover': { transform: 'translateY(-2px)' },
    },
    thumbWrap: {
        aspectRatio: '16 / 10',
        backgroundColor: '#fff',
        overflow: 'hidden',
    },
    thumb: {
        width: '100%',
        height: '100%',
        objectFit: 'cover',
        display: 'block',
    },
    thumbPlaceholder: {
        width: '100%',
        height: '100%',
        backgroundColor: '#444',
    },
    meta: {
        padding: 12,
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    name: {
        fontWeight: 500,
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
    },
    stats: {
        opacity: 0.7,
        fontSize: 14,
    },
    status: {
        opacity: 0.7,
        padding: 24,
    },
    loadMore: {
        display: 'block',
        margin: '24px auto',
        padding: '10px 24px',
        border: 'none',
        borderRadius: 8,
        background: theme.colors?.buttonBackground || '#333',
        color: 'inherit',
        cursor: 'pointer',
    },
    deleteBtn: {
        background: 'transparent',
        border: 'none',
        color: 'inherit',
        cursor: 'pointer',
        opacity: 0.5,
        fontSize: 18,
        '&:hover': { opacity: 1 },
    },
    draftMeta: {
        padding: '0 12px 12px',
        fontSize: 12,
        opacity: 0.5,
    },
}));
