import { createUseStyles } from 'react-jss';

export const useStyles = createUseStyles(theme => ({
    container: {
        padding: 24,
        color: theme.colors?.mainText || '#333',
        maxWidth: 720,
        margin: '0 auto',
    },
    header: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    title: { margin: 0, fontSize: 28 },
    back: {
        color: 'inherit',
        opacity: 0.7,
        textDecoration: 'none',
        '&:hover': { opacity: 1, textDecoration: 'underline' },
    },
    table: {
        width: '100%',
        borderCollapse: 'collapse',
        background: theme.colors?.paper || '#fff',
        borderRadius: 12,
        overflow: 'hidden',
        '& td': {
            padding: '12px 16px',
            borderTop: `1px solid ${theme.colors?.scrollbarBackground || 'rgba(0,0,0,0.08)'}`,
        },
        '& tr:first-child td': { borderTop: 'none' },
    },
    action: { width: '50%' },
    comboCell: { width: '40%' },
    resetCell: { width: '10%', textAlign: 'right' },
    combo: {
        border: `1px solid ${theme.colors?.selectedOutline || 'rgba(0,0,0,0.15)'}`,
        background: 'transparent',
        color: 'inherit',
        padding: '6px 12px',
        borderRadius: 6,
        fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
        fontSize: 14,
        cursor: 'pointer',
        minWidth: 120,
        textAlign: 'center',
        '&:hover': { borderColor: theme.colors?.buttonBackground || '#ff00a2' },
    },
    comboCapturing: {
        background: theme.colors?.buttonBackground || '#ff00a2',
        color: theme.colors?.buttonText || '#fff',
        padding: '6px 12px',
        border: 'none',
        borderRadius: 6,
        fontSize: 14,
        cursor: 'pointer',
        minWidth: 120,
    },
    reset: {
        background: 'transparent',
        border: 'none',
        color: theme.colors?.buttonBackground || '#ff00a2',
        cursor: 'pointer',
        fontSize: 13,
        padding: 4,
    },
    conflict: {
        background: 'rgba(255, 180, 50, 0.15)',
        border: `1px solid rgba(255, 150, 50, 0.35)`,
        padding: 16,
        borderRadius: 8,
        marginBottom: 16,
    },
}));
