export const SHORTCUTS = {
    UNDO: 'undo',
    CLEAR_FRAME: 'clearFrame',
    SAVE: 'save',
    DUPLICATE_FRAME: 'duplicateFrame',
    ONION_SKIN_TOOL: 'onionSkinTool',
    ADD_FRAME: 'addFrame',
    REDO: 'redo',
    REDUCE_BRUSH: 'reduceBrush',
    INCREASE_BRUSH: 'increaseBrush',
    PLAY_PAUSE: 'playPause',
    BRUSH_TOOL: 'brushTool',
    ERASER_TOOL: 'eraserTool',
    DELETE_FRAME: 'deleteFrame',
    NEXT_FRAME: 'nextFrame',
    PREVIOUS_FRAME: 'previousFrame',
}

export const shortcuts = {
    undo: { key: 'Z', code: 'KeyZ', ctrlKey: true },
    clearFrame: { key: 'Backspace', code: 'Backspace', ctrlKey: true },
    save: { key: 'S', code: 'KeyS', ctrlKey: true },
    duplicateFrame: { key: 'D', code: 'KeyD', ctrlKey: true },
    onionSkinTool: { key: 'O', code: 'KeyO', ctrlKey: true },
    addFrame: { key: '>', code: 'Period', ctrlKey: true },
    redo: { key: 'Z', code: 'KeyZ', ctrlKey: true, shiftKey: true },
    reduceBrush: { key: '[', code: 'BracketLeft'},
    increaseBrush: { key: ']', code: 'BracketRight'},
    playPause: {key: 'Space', code: 'Space'},
    brushTool: { key: 'B', code: 'KeyB' },
    eraserTool: { key: 'E', code: 'KeyE' },
    deleteFrame: { key: 'Delete', code: 'Delete' },
    nextFrame: { key: '>', code: 'Period' },
    previousFrame: { key: '<', code: 'Comma' },
}

//[ShortcutKeys.SELECT_ALL_MARKUP_SHORTCUT]: { key: 'A', code: 'KeyA', ctrlKey: true },
//     [ShortcutKeys.ARROW_SHORTCUT]: { key: 'A', code: 'KeyA', ctrlKey: true, altKey: true },
//     [ShortcutKeys.TEXT_SHORTCUT]: { key: 'T', code: 'KeyT', ctrlKey: true, altKey: true },
//     [ShortcutKeys.RECTANGLE_SHORTCUT]: { key: 'R', code: 'KeyR', ctrlKey: true, altKey: true },
//     [ShortcutKeys.ROUNDED_RECTANGLE_SHORTCUT]: { key: 'U', code: 'KeyU', ctrlKey: true, altKey: true },
//     [ShortcutKeys.ELLIPSE_SHORTCUT]: { key: 'O', code: 'KeyO', ctrlKey: true, altKey: true },
//     [ShortcutKeys.LINE_SHORTCUT]: { key: 'L', code: 'KeyL', ctrlKey: true, altKey: true },
//     [ShortcutKeys.MARKER_SHORTCUT]: { key: 'M', code: 'KeyM', ctrlKey: true, altKey: true },
//     [ShortcutKeys.HIGHLIGHTER_SHORTCUT]: { key: 'I', code: 'KeyI', ctrlKey: true, altKey: true },
//     [ShortcutKeys.STAMP_SHORTCUT]: { key: 'P', code: 'KeyP', ctrlKey: true, altKey: true },
//     [ShortcutKeys.PIXELATE_SHORTCUT]: { key: 'X', code: 'KeyX', ctrlKey: true, altKey: true },
//     [ShortcutKeys.CROP_SHORTCUT]: { key: 'K', code: 'KeyK', ctrlKey: true, altKey: true },
//     [ShortcutKeys.ZOOM_IN_SHORTCUT]: { key: '=', code: 'Equal', ctrlKey: true },
//     [ShortcutKeys.ZOOM_OUT_SHORTCUT]: { key: '-', code: 'Minus', ctrlKey: true },
//     [ShortcutKeys.ZOOM_TO_FIT_SHORTCUT]: { key: '0', code: 'Digit0', ctrlKey: true },
//     [ShortcutKeys.ZOOM_TO_ORIGINAL_SHORTCUT]: { key: '1', code: 'Digit1', ctrlKey: true },
//     [ShortcutKeys.UNDO_SHORTCUT]: { key: 'Z', code: 'KeyZ', ctrlKey: true },
//     [ShortcutKeys.REDO_SHORTCUT]: { key: 'Z', code: 'KeyZ', ctrlKey: true, shiftKey: true }