export const SHORTCUTS = {
    UNDO: 'undo',
    REDO: 'redo',
    SAVE: 'save',
    CLEAR_FRAME: 'clearFrame',
    DUPLICATE_FRAME: 'duplicateFrame',
    ONION_SKIN_TOOL: 'onionSkinTool',
    ADD_FRAME: 'addFrame',
    ADD_LAYER: 'addLayer',
    REDUCE_BRUSH: 'reduceBrush',
    INCREASE_BRUSH: 'increaseBrush',
    PLAY_PAUSE: 'playPause',
    BRUSH_TOOL: 'brushTool',
    ERASER_TOOL: 'eraserTool',
    DELETE_FRAME: 'deleteFrame',
    NEXT_FRAME: 'nextFrame',
    PREVIOUS_FRAME: 'previousFrame',
    ZOOM_IN: 'zoomIn',
    ZOOM_OUT: 'zoomOut',
    ZOOM_RESET: 'zoomReset',
};

export const SHORTCUT_LABELS = {
    [SHORTCUTS.UNDO]: 'Undo',
    [SHORTCUTS.REDO]: 'Redo',
    [SHORTCUTS.SAVE]: 'Publish / save',
    [SHORTCUTS.CLEAR_FRAME]: 'Clear frame',
    [SHORTCUTS.DUPLICATE_FRAME]: 'Duplicate frame',
    [SHORTCUTS.ONION_SKIN_TOOL]: 'Toggle onion skin',
    [SHORTCUTS.ADD_FRAME]: 'Add frame',
    [SHORTCUTS.ADD_LAYER]: 'Add layer',
    [SHORTCUTS.REDUCE_BRUSH]: 'Smaller brush',
    [SHORTCUTS.INCREASE_BRUSH]: 'Bigger brush',
    [SHORTCUTS.PLAY_PAUSE]: 'Play / pause',
    [SHORTCUTS.BRUSH_TOOL]: 'Brush tool',
    [SHORTCUTS.ERASER_TOOL]: 'Eraser tool',
    [SHORTCUTS.DELETE_FRAME]: 'Delete frame',
    [SHORTCUTS.NEXT_FRAME]: 'Next frame',
    [SHORTCUTS.PREVIOUS_FRAME]: 'Previous frame',
    [SHORTCUTS.ZOOM_IN]: 'Zoom in',
    [SHORTCUTS.ZOOM_OUT]: 'Zoom out',
    [SHORTCUTS.ZOOM_RESET]: 'Reset zoom',
};

// Combo format: `Modifiers+Code` where Modifiers ∈ {Ctrl, Alt, Shift, Meta}
// and Code is an `e.code` value (layout-independent). E.g. "Ctrl+KeyZ", "Space".
export const DEFAULT_SHORTCUTS = {
    [SHORTCUTS.UNDO]: 'Ctrl+KeyZ',
    [SHORTCUTS.REDO]: 'Ctrl+Shift+KeyZ',
    [SHORTCUTS.SAVE]: 'Ctrl+KeyS',
    [SHORTCUTS.CLEAR_FRAME]: 'Ctrl+Backspace',
    [SHORTCUTS.DUPLICATE_FRAME]: 'Ctrl+KeyD',
    [SHORTCUTS.ONION_SKIN_TOOL]: 'KeyO',
    [SHORTCUTS.ADD_FRAME]: 'KeyN',
    [SHORTCUTS.ADD_LAYER]: 'KeyL',
    [SHORTCUTS.REDUCE_BRUSH]: 'BracketLeft',
    [SHORTCUTS.INCREASE_BRUSH]: 'BracketRight',
    [SHORTCUTS.PLAY_PAUSE]: 'Space',
    [SHORTCUTS.BRUSH_TOOL]: 'KeyB',
    [SHORTCUTS.ERASER_TOOL]: 'KeyE',
    [SHORTCUTS.DELETE_FRAME]: 'Delete',
    [SHORTCUTS.NEXT_FRAME]: 'ArrowRight',
    [SHORTCUTS.PREVIOUS_FRAME]: 'ArrowLeft',
    [SHORTCUTS.ZOOM_IN]: 'Ctrl+Equal',
    [SHORTCUTS.ZOOM_OUT]: 'Ctrl+Minus',
    [SHORTCUTS.ZOOM_RESET]: 'Ctrl+Digit0',
};
